version: v.1.0.0
pidfile: ./storedata_server.pid
retrystartup: true
prest:
  database: exampledb
  schema: public
  hosts: 192.168.2.80:6000
  jwt:
    secret: mysecret
    expired: 120s
listen:
  hosts: [":8087"]
  enablecors: true
logger:
    logfile: ./logs/storedata_server.log
    loglevel: info
    logsize: 20971520
...
